---
- name: Create the ca user
  user:
    name: ca
    system: yes
    state: present

- name: Ensure /etc/inspec exists
  file:
    path: /etc/inspec
    state: directory

- name: Ensure /etc/cfssl exists
  file:
    path: /etc/cfssl
    state: directory
    owner: ca
    group: ca

- name: Copy key files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0400
    owner: ca
    group: ca
  loop:
    - {src: "ca-key.pem", dest: "/etc/cfssl/ca-key.pem" }
    - {src: "ca.pem", dest: "/etc/cfssl/ca.pem" }
    - {src: "ca-server-key.pem", dest: "/etc/cfssl/ca-server-key.pem" }
    - {src: "ca-server.pem", dest: "/etc/cfssl/ca-server.pem" }

- name: Render configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0400
    owner: ca
    group: ca
  loop:
    - {src: "config.json.j2", dest: "/etc/cfssl/config.json" }

- name: Copy systemd service
  copy:
    src: cfssl.service
    dest: /lib/systemd/system/cfssl.service
    owner: root
    group: root

- name: Copy InSpec profile
  copy:
    src: certificate-authority-1.0.0.tar.gz
    dest: /etc/inspec/certificate-authority-1.0.0.tar.gz

- name: Start cfssl server
  systemd:
    daemon_reload: yes
    name: cfssl
    enabled: yes
    state: started
