---
- name: Create users
  user:
    name: "{{ item.name }}"
    group: sudo
    append: yes
    state: present
    shell: /bin/bash
  with_items: "{{ authorized_users }}"
- name: Add authorized keys
  authorized_key:
    user: "{{item.name}}"
    state: present
    key: "{{item.key}}"
  with_items: "{{ authorized_users }}"
- name: Install package dependencies
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - python-pip
- name: Upgrade pip
  pip:
    name: pip
    state: latest
- name: Install PyOpenSSL module
  pip:
    name: pyopenssl
    state: latest
- name: Create directory for combining certificate files
  file:
    path: /etc/ssl/private/chain.d
    state: directory
- name: Generate RSA private key for letsencrypt
  openssl_privatekey:
    path: "{{letsencrypt_account_key}}"
- name: Generate TLS private key
  openssl_privatekey:
    path: "{{tls_private_key_path}}"
- name: Generate TLS public key
  openssl_publickey:
    path: "{{tls_public_key_path}}"
    privatekey_path: "{{tls_private_key_path}}"
- name: Generate TLS certificate request.
  openssl_csr:
    path: "{{tls_certificate_request_path}}"
    privatekey_path: "{{tls_private_key_path}}"
    subjectAltName: "DNS:{{domain}}"
- name: Request the TLS certificate.
  letsencrypt:
    account_key: "{{letsencrypt_account_key}}"
    acme_directory: "{{letsecnrypt_acme_directory}}"
    csr: "{{tls_certificate_request_path}}"
    dest: "{{tls_certificate_output_path}}"
  register: challenge
- name: Make the /var/www/html/.well-known/acme-challenge directory
  file:
    path: /var/www/html/.well-known/acme-challenge
    state: directory
- name: Prepare to respond to the challenge.
  copy:
    dest: /var/www/html/{{ challenge['challenge_data']['uwsg.tech']['http-01']['resource'] }}
    content: "{{ challenge['challenge_data']['uwsg.tech']['http-01']['resource_value'] }}"
  when: challenge|changed
- name: Make sure LigHTTPd is started.
  service:
    name: lighttpd
    state: started
- name: Respond to the challenge.
  letsencrypt:
    account_key: "{{letsencrypt_account_key}}"
    acme_directory: "{{letsecnrypt_acme_directory}}"
    csr: "{{tls_certificate_request_path}}"
    dest: "{{tls_certificate_output_path}}"
    data: "{{ challenge }}"
- name: Make sure LigHTTPd is stopped.
  service:
    name: lighttpd
    state: stopped
- name: Place the Let's Encrypt intermediate certificate.
  copy:
    src: chain.pem
    dest: "{{tls_chain_path}}"
- name: Assemble the certificate chain file.
  assemble:
    src: /etc/ssl/private/chain.d
    dest: "{{tls_certificate_chain_path}}"
- name: Render the GitLab configuration template.
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    mode: '0600'
- name: Run gitlab-ctl reconfigure, which starts the actual service.
  command: gitlab-ctl reconfigure
- name: Remove the annoying setup prompt on the root account every time we log in.
  file:
    path: /etc/update-motd.d/99-one-click
    state: absent