---
- name: Q1 CentOS 6.6 setup
  hosts: default
  tasks:
  - name: Print message
    debug: msg="Beginning of CentOS 6.6 configuration Ansible script."

  - name: Print Lab 1a group add message
    debug: msg="Add a new group, admin, to the system."

  - name: Add group admin
    command: /usr/sbin/groupadd admin
    become: true
    become_method: sudo
    become_user: root

  - name: Print Lab 1a users add message
    debug: msg="Add two new users to the system; q1u1, q2u2."

  - name: Add user q1u1
    command: /usr/sbin/useradd -c "Q1C6 User1" -G admin q1u1
    become: true
    become_method: sudo
    become_user: root

  - name: Add user q1u2
    command: /usr/sbin/useradd -c "Q1C6 User2" -G admin q1u2
    become: true
    become_method: sudo
    become_user: root

  - name: Update yum cashe
    yum: name='*' state=latest
    become: true
    become_method: sudo
    become_user: root  
