---
- name: Allow connections on the dummy interface
  iptables:
    chain: INPUT
    in_interface: dummy0
    jump: ACCEPT

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: "dummy0.network", dest: "/etc/systemd/network/dummy0.network"}
    - {src: "dummy0.netdev", dest: "/etc/systemd/network/dummy0.netdev"}

- name: Restart systemd-networkd
  systemd:
    name: "systemd-networkd"
    enabled: yes
    state: restarted

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Copy configuration file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: "resolved.conf", dest: "/etc/systemd/resolved.conf"}
    - {src: "consul-dnsmasq", dest: "/etc/dnsmasq.d/consul-over-dummy-interface"}

- name: Stop dnsmasq
  systemd:
    daemon_reload: yes
    name: "dnsmasq"
    enabled: yes
    state: stopped

- name: Restart dnsmasq
  systemd:
    name: "dnsmasq"
    state: restarted

- name: Stop systemd-resolved
  systemd:
    name: "systemd-resolved"
    state: stopped

- name: Restart systemd-resolved
  systemd:
    name: "systemd-resolved"
    state: started
