---
# Add third party repositories
- name: Add Docker repository key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty edge
    state: present

- name: Install packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - docker-ce

- name: Install Python package
  pip:
    name: docker-py
    state: latest

