---
- hosts: gitlab
  tasks:
  - name: Include all the role variables.
    include_vars:
      dir: roles/gitlab/vars
  - name: Reset user passwords
    command: passwd -d -e "{{item.name}}"
    with_items: "{{ authorized_users }}"
