---

- name: Install baseline required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - unzip
    - python3-pip

- name: Install pexpect
  pip:
    name: pexpect

- name: Download Hashicorp tools
  get_url:
    url: '{{ item.url }}'
    checksum: '{{ item.checksum }}'
    dest: '{{ item.dest }}'
  loop:
    - { url: "https://releases.hashicorp.com/consul/1.1.0/consul_1.1.0_linux_amd64.zip", dest: "/tmp/consul_1.1.0_linux_amd64.zip", checksum: "sha256:09c40c8b5be868003810064916d8460bff334ccfb59a5046390224b27e052c45" }
    - { url: "https://releases.hashicorp.com/vault/0.10.2/vault_0.10.2_linux_amd64.zip", dest: "/tmp/vault_0.10.2_linux_amd64.zip", checksum: "sha256:f725be68316d10ef2e7779fdedd8eb5d4ed9975303c828466bb9a729e01392dd" }
    - { url: "https://releases.hashicorp.com/nomad/0.8.4/nomad_0.8.4_linux_amd64.zip", dest: "/tmp/nomad_0.8.4_linux_amd64.zip", checksum: "sha256:42fc455d09ea0085cc79d7be4fb2089a9ab7db3cc2e8047e8437855a81b090e9"}

- name: Install Hashicorp tools
  unarchive:
    src: '{{ item }}'
    dest: /usr/bin
    remote_src: yes
  loop:
    - "/tmp/consul_1.1.0_linux_amd64.zip"
    - "/tmp/vault_0.10.2_linux_amd64.zip"
    - "/tmp/nomad_0.8.4_linux_amd64.zip"

- name: Create configuration directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - "/etc/consul"
    - "/etc/vault"
    - "/etc/nomad"

- name: Render configuration templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "{{ consul_template_file }}", dest: "/etc/consul/consul-config.json" }
    - { src: "{{ nomad_template_file }}", dest: /etc/nomad/config.hcl }
    - { src: "vault.hcl.j2", dest: /etc/vault/config.hcl }

- name: Set environment variables
  lineinfile:
    line: "{{ item }}"
    path: /etc/environment
  loop:
    - "CONSUL_HTTP_ADDR=https://localhost:8500"
    - "CONSUL_CLIENT_KEY=/etc/ssl/cert-key.pem"
    - "CONSUL_CLIENT_CERT=/etc/ssl/cert.pem"
    - "NOMAD_ADDR=https://localhost:4646"
    - "NOMAD_CLIENT_KEY=/etc/ssl/cert-key.pem"
    - "NOMAD_CLIENT_CERT=/etc/ssl/cert.pem"
    - "VAULT_CLIENT_KEY=/etc/ssl/cert-key.pem"
    - "VAULT_CLIENT_CERT=/etc/ssl/cert.pem"

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "consul.service", dest: "/lib/systemd/system/consul.service"}
    - { src: "vault.service", dest: "/lib/systemd/system/vault.service"}
    - { src: "nomad.service", dest: "/lib/systemd/system/nomad.service"}
    - { src: "nomad-server-policy.hcl", dest: "/etc/vault/nomad-server-policy.hcl"}
    - { src: "nomad-cluster-role.json", dest: "/etc/vault/nomad-cluster-role.json"}

- name: Start services
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - "consul"
    - "vault"
