---
- hosts: all
  gather_facts: False
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:

- hosts: all
  roles:
    - iptables-base

- hosts: compute
  roles:
    - docker
  
- hosts: ca
  roles:
    - ca

- hosts: control
  roles:
    - consul-server
    - nomad-server

- hosts: loadbalancer
  roles:
    - loadbalancer

- hosts: compute
  roles:
    - consul-client
    - nomad-client

- hosts: hashicorp
  roles:
    - vault

- hosts: hashicorp
  roles:
    - nomad
