---
- hosts: all
  gather_facts: False
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:

- hosts: all
  tasks: [ ]
  
- hosts: ca
  roles:
    - ca

- hosts: hashicorp
  roles:
    - hashicorp
