- name: Install baseline required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 300
  loop:
    - unzip
    - python3-pip
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - jq

- name: Install pexpect
  pip:
    name: pexpect
