---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    id: 0A9AF2115F4687BD29803A206B73A36E6026DFCA
    state: present

- apt_repository:
    repo: deb https://dl.bintray.com/rabbitmq/debian artful main
    state: present

- name: Install RabbitMQ Server
  apt:
    name: rabbitmq-server
    state: latest
    update_cache: yes
  notify: restart rabbitmq

- name: Enable the Management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- name: Create administration user
  rabbitmq_user:
    user: admin
    password: "{{ rabbitmq_admin_password }}"
    tags: administrator

- name: Delete old-style configuration file.
  file:
    path: /etc/rabbitmq/rabbitmq.config
    state: absent

- name: Copy configuration file.
  template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
  notify: restart rabbitmq

- name: Ensure RabbitMQ is started
  systemd:
    name: rabbitmq-server
    state: started
