---

- name: Ensure directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/tls
    - /etc/tls/private
    - /etc/tls/csr
    - /etc/tls/cert

- name: Notice if /etc/tls/private/node.pem exists
  stat:
    path: /etc/tls/private/node.pem
  register: priv

- name: Create EC params
  shell: openssl ecparam -name secp384r1 -out /tmp/curve

- name: Create self-signed certificate
  shell: >
    openssl req -x509 -nodes -days 365
    -newkey ec:/tmp/curve
    -keyout /etc/tls/private/node.pem
    -out /etc/tls/cert/node.crt
    -subj '/CN={{ ansible_hostname }}.uwsg.tech/O=University of Washington Linux Study Group/C=US'
