---
- name: Allow incoming TCP connections
  iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    comment: "{{ item.comment }}"
    ctstate: NEW
    syn: match
    jump: ACCEPT
  loop:
    - { port: 80, protocol: "tcp", comment: "Allow HTTP over plaintext" }
    - { port: 443, protocol: "tcp", comment: "Allow HTTP over TLS" }

- name: Download Consul Template
  get_url:
    url: https://releases.hashicorp.com/consul-template/0.19.5/consul-template_0.19.5_linux_amd64.tgz
    checksum: sha256:39f4fc2ffaa00e0a7504f531f922d9d39dd29520c03dc0abde46835ebd52c647
    dest: /usr/bin/consul-template.tgz

- name: Install Consul Template
  unarchive:
    remote_src: yes
    src: /usr/bin/consul-template.tgz
    dest: /usr/bin
    mode: 0755
    owner: root

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "consul-template.service", dest: "/lib/systemd/system/consul-template.service" }
    - { src: "consul-template.hcl", dest: "/etc/consul-template.hcl" }
    - { src: "haproxy.cfg.ctmpl", dest: "/etc/haproxy/haproxy.cfg.ctmpl" }
    - { src: "loadbalancers-1.0.0.tar.gz", dest: "/etc/inspec/loadbalancers-1.0.0.tar.gz" }

- name: Start services
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - haproxy
    - consul-template
