---
- name: Allow incoming connections
  iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    comment: "{{ item.comment }}"
    ctstate: NEW
    syn: match
    jump: ACCEPT
  loop:
    - { port: 8125, protocol: "tcp", comment: "Allow Vault telemetry" }
    - { port: 8200, protocol: "tcp", comment: "Allow Vault HTTP" }
    - { port: 8201, protocol: "tcp", comment: "Allow Vault Discovery" }

- name: Render configuration template
  template:
    src: "config.hcl.j2"
    dest: /etc/vault/config.hcl

- name: Set environment variables
  lineinfile:
    line: "{{ item }}"
    path: /etc/environment
  loop:
    - "VAULT_CLIENT_KEY=/etc/ssl/cert-key.pem"
    - "VAULT_CLIENT_CERT=/etc/ssl/cert.pem"

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "vault.service", dest: "/lib/systemd/system/vault.service"}
    - { src: "nomad-server-policy.hcl", dest: "/etc/vault/nomad-server-policy.hcl"}
    - { src: "nomad-cluster-role.json", dest: "/etc/vault/nomad-cluster-role.json"}

- name: Start service
  systemd:
    daemon_reload: yes
    name: "vault"
    enabled: yes
    state: started
