---
- name: Become cluster leader.
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16 2>/dev/null | grep "kubeadm join --token" | sed -e 's/^[[:space:]]*//'
  register: kubeadm_join

- name: Print the bootstrap token so that we know we got it.
  debug: msg="{{kubeadm_join.stdout}}"

- name: Create nonprivileged user
  user:
    name: nonprivileged
    state: present
    shell: /bin/bash
    groups:
      - systemd-journal

- name: Setup home directory
  file:
    path: /home/nonprivileged/.kube
    owner: nonprivileged
    state: directory

- name: Copy configuration file to Kube directory.
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/nonprivileged/.kube/config
    owner: nonprivileged
    remote_src: yes