---
- name: Render configuration template
  template:
    src: "config.json.j2"
    dest: "/etc/consul/config.json"

- name: Start service
  systemd:
    daemon_reload: yes
    name: "consul"
    enabled: yes
    state: started
