---
- name: Create configuration directory
  file:
    path: /etc/vault
    state: directory

- name: Render vault.hcl
  template:
    src: vault.hcl.j2
    dest: /etc/vault/vault.hcl
    mode: 0400

- name: Copy vault systemd unit file
  copy:
    src: vault.service
    dest: /lib/systemd/system/vault.service

- name: Start vault
  systemd:
    name: vault
    daemon_reload: yes
    enabled: yes
    state: started
