---
- name: Create configuration directory
  file:
    path: /etc/vault
    state: directory

- name: Render vault.hcl
  template:
    src: vault.hcl.j2
    dest: /etc/vault/vault.hcl
    mode: 0400

- name: Set environment variables
  lineinfile:
    line: "{{ item }}"
    path: /etc/environment
  loop:
    - "VAULT_CLIENT_KEY=/etc/ssl/cert-key.pem"
    - "VAULT_CLIENT_CERT=/etc/ssl/cert.pem"

- name: Copy vault systemd unit file
  copy:
    src: vault.service
    dest: /lib/systemd/system/vault.service

- name: Start vault
  systemd:
    name: vault
    daemon_reload: yes
    enabled: yes
    state: started
