---
- name: Download
  get_url:
    url: "https://releases.hashicorp.com/consul/1.2.0/consul_1.2.0_linux_amd64.zip"
    checksum: "sha256:85d84ea3f6c68d52549a29b00fd0035f72c2eabff672ae46ca643cb407ef94b4"
    dest: "/tmp/consul.zip"

- name: Install
  unarchive:
    src: "/tmp/consul.zip"
    dest: /usr/bin
    remote_src: yes

- name: Create configuration directory
  file:
    path: "/etc/consul"
    state: directory

- name: Set environment variables
  lineinfile:
    line: "{{ item }}"
    path: /etc/environment
  loop:
    - "CONSUL_HTTP_ADDR=https://localhost:8500"
    - "CONSUL_CLIENT_KEY=/etc/ssl/cert-key.pem"
    - "CONSUL_CLIENT_CERT=/etc/ssl/cert.pem"

- name: Copy configuration files
  copy:
    src: "consul.service"
    dest: "/lib/systemd/system/consul.service"
