---
- name: Allow connections on the dummy interface
  iptables:
    chain: INPUT
    in_interface: dummy0
    jump: ACCEPT

- name: Allow incoming TCP connections
  iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    comment: "{{ item.comment }}"
    ctstate: NEW
    syn: match
    jump: ACCEPT
  loop:
    - { port: 8300, protocol: "tcp", comment: "Allow Consul server RPC" }
    - { port: 8301, protocol: "tcp", comment: "Allow Consul Serf LAN" }
    - { port: 8302, protocol: "tcp", comment: "Allow Consul Serf WAN" }
    - { port: 8500, protocol: "tcp", comment: "Allow Consul HTTP" }
    - { port: 8600, protocol: "tcp", comment: "Allow Consul DNS" }

- name: Allow incoming UDP connections
  iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    comment: "{{ item.comment }}"
    jump: ACCEPT
  loop:
    - { port: 8301, protocol: "udp", comment: "Allow Consul Serf LAN" }
    - { port: 8302, protocol: "udp", comment: "Allow Consul Serf WAN" }
    - { port: 8600, protocol: "udp", comment: "Allow Consul DNS" }

- name: Download
  get_url:
    url: "https://releases.hashicorp.com/consul/1.2.1/consul_1.2.1_linux_amd64.zip"
    checksum: "sha256:e4146334be453146890023303da3e0c815669e108a18fb7d742745df3414a31a"
    dest: "/tmp/consul.zip"

- name: Install
  unarchive:
    src: "/tmp/consul.zip"
    dest: /usr/bin
    remote_src: yes

- name: Create configuration directory
  file:
    path: "/etc/consul"
    state: directory

- name: Set environment variables
  lineinfile:
    line: "{{ item }}"
    path: /etc/environment
  loop:
    - "CONSUL_HTTP_ADDR=https://localhost:8500"
    - "CONSUL_CLIENT_KEY=/etc/ssl/cert-key.pem"
    - "CONSUL_CLIENT_CERT=/etc/ssl/cert.pem"

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Copy configuration file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: "consul.service", dest: "/lib/systemd/system/consul.service"}
    - {src: "consul-dnsmasq", dest: "/etc/dnsmasq.d/consul"}
    - {src: "resolved.conf", dest: "/etc/systemd/resolved.conf"}
    - {src: "dummy0.network", dest: "/etc/systemd/network/dummy0.network"}
    - {src: "dummy0.netdev", dest: "/etc/systemd/network/dummy0.netdev"}

- name: Restart systemd-networkd
  systemd:
    name: "systemd-networkd"
    enabled: yes
    state: restarted

- name: Stop dnsmasq
  systemd:
    daemon_reload: yes
    name: "dnsmasq"
    enabled: yes
    state: stopped

- name: Restart dnsmasq
  systemd:
    name: "dnsmasq"
    state: started

- name: Stop systemd-resolved
  systemd:
    name: "systemd-resolved"
    state: stopped

- name: Restart systemd-resolved
  systemd:
    name: "systemd-resolved"
    state: started
