---
- name: Allow incoming TCP connections
  iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    comment: "{{ item.comment }}"
    ctstate: NEW
    syn: match
    jump: ACCEPT
  loop:
    - { port: 8300, protocol: "tcp", comment: "Allow Consul server RPC" }
    - { port: 8301, protocol: "tcp", comment: "Allow Consul Serf LAN" }
    - { port: 8302, protocol: "tcp", comment: "Allow Consul Serf WAN" }
    - { port: 8500, protocol: "tcp", comment: "Allow Consul HTTP" }
    - { port: 8600, protocol: "tcp", comment: "Allow Consul DNS" }

- name: Allow incoming UDP connections
  iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    comment: "{{ item.comment }}"
    jump: ACCEPT
  loop:
    - { port: 8301, protocol: "udp", comment: "Allow Consul Serf LAN" }
    - { port: 8302, protocol: "udp", comment: "Allow Consul Serf WAN" }
    - { port: 8600, protocol: "udp", comment: "Allow Consul DNS" }

- name: Ensure directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/etc/consul"
    - /etc/inspec"

- name: Set environment variables
  lineinfile:
    line: "{{ item }}"
    path: /etc/environment
  loop:
    - "CONSUL_HTTP_ADDR=https://localhost:8500"
    - "CONSUL_CLIENT_KEY=/etc/ssl/cert-key.pem"
    - "CONSUL_CLIENT_CERT=/etc/ssl/cert.pem"

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: "consul.service", dest: "/lib/systemd/system/consul.service"}
    - {src: "consul-dnsmasq", dest: "/etc/dnsmasq.d/consul"}
    - {src: "resolved.conf", dest: "/etc/systemd/resolved.conf"}
    - {src: "control-plane-1.0.0.tar.gz", dest: "/etc/inspec/control-plane-1.0.0.tar.gz"}

- name: Stop dnsmasq
  systemd:
    daemon_reload: yes
    name: "dnsmasq"
    enabled: yes
    state: stopped

- name: Restart dnsmasq
  systemd:
    name: "dnsmasq"
    state: started

- name: Stop systemd-resolved
  systemd:
    name: "systemd-resolved"
    state: stopped

- name: Restart systemd-resolved
  systemd:
    name: "systemd-resolved"
    state: started
