---
- name: Allow incoming traffic from interfaces
  iptables:
    chain: INPUT
    in_interface: "{{ item }}"
    jump: ACCEPT
  loop:
    - "lo"
    - "{{ private_network_interface }}"

- name: Allow incoming ICMP traffic
  iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT

- name: Allow incoming traffic on standard ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
  loop:
    - 22
    - 443

- name: Allow incoming related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Set default DROP policy
  iptables:
    chain: INPUT
    policy: DROP
