---
- name: Allow incoming from specific interfaces
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  loop:
    - "lo"
    - "{{ private_network_interface }}"

- name: Allow incoming SSH connections
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
  loop:
    - 22
    - 443

- name: Allow incoming related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Set default DROP policy
  iptables:
    chain: INPUT
    policy: DROP
