---
- name: Allow incoming from the loopback address
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Allow incoming SSH connections
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.

- name: Allow incoming HTTP over TLS
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
    comment: Accept HTTP/TLS connections

- name: Allow incoming related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

# Change this to DROP at some point
- name: Set default DROP policy
  iptables:
    chain: INPUT
    policy: DROP
