---
- name: "Add /etc/hosts entry for CA server"
  lineinfile: 
    dest: /etc/hosts
    regexp: '.*{{ hostvars[item].ansible_hostname }}$'
    line: "{{ hostvars[item][hostvars[item]['ansible_interface_variable']]['ipv4']['address'] }} {{ hostvars[item].ansible_hostname }} {{ hostvars[item].ansible_hostname }}.cluster.local"
    state: present
  when: hostvars[item][hostvars[item]['ansible_interface_variable']]['ipv4']['address'] is defined
  with_items: "{{ groups['ca'] }}"

- name: "Add /etc/hosts entries for control servers"
  lineinfile: 
    dest: /etc/hosts
    regexp: '.*{{ hostvars[item].ansible_hostname }}$'
    line: "{{ hostvars[item][hostvars[item]['ansible_interface_variable']]['ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}.cluster.local"
    state: present
  when: hostvars[item][hostvars[item]['ansible_interface_variable']]['ipv4']['address'] is defined
  with_items: "{{ groups['control'] }}"

- name: Copy Example Root CA certificate
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  loop:
    - {src: "ca.pem", dest: "/usr/local/share/ca-certificates/Example_Root_CA.crt" }

- name: Update TLS roots
  shell: update-ca-certificates

- name: Install cfssl
  apt:
    name:
      - golang-cfssl
    cache_valid_time: 240
