---

- name: Install Aptitude
  apt:
    name: "{{item}}"
    state: latest
  loop:
    - aptitude

- name: Update package cache
  apt:
    autoremove: yes
    update_cache: yes
    upgrade: yes

- name: Install packages
  apt:
    name: "{{item}}"
    state: latest
  loop:
    - python3-pip

